### ISSUE TITLE
Trawl reports the last IPv4 as the address of an interface, not the first

### ISSUE THREAD

**Issue by siebenmann** [robphoenix/trawl#19]
If you have an interface with multiple IP addresses attached to it, trawl reports the last IPv4 address of the interface (and probably the last IPv6 interface). Traditionally one would report the first IP if you're only going to report one, because that is usually the primary IP address.

```
$ ip -4 addr list eno1
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 128.100.3.124/24 brd 128.100.3.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet 128.100.3.125/24 brd 128.100.3.255 scope global secondary eno1:1
       valid_lft forever preferred_lft forever
    inet 128.100.3.126/24 brd 128.100.3.255 scope global secondary eno1:2
       valid_lft forever preferred_lft forever
    inet 128.100.3.127/24 brd 128.100.3.255 scope global secondary eno1:3
       valid_lft forever preferred_lft forever
    inet 128.100.3.128/24 brd 128.100.3.255 scope global secondary eno1:4
       valid_lft forever preferred_lft forever
$ trawl -f eno1
eno1  128.100.3.128  255.255.255.0  128.100.3.0/24  1500  d4:ae:52:cb:c2:2c  fe80::d6ae:52ff:fecb:c22c/64
```

I think that the broad fix for this would be to change `extractAddrs()` to return a list of IPv4 and IPv6 addresses, instead of trying to return just one of each. The current `New()` could then use the first one of each.

**Comment by robphoenix** [comment]
Ah interesting, thanks @siebenmann for bringing this to my attention. I'll get this fixed, may not be until next week though. Unless you fancy submitting a PR?

**Comment by siebenmann** [comment]
I'll see if I can take a shot at this and successfully navigate the PR process to get the proposed change to you.

I just noticed that this applies to IPv6 addresses too, basically as expected. This is a bit more annoying in the IPv6 case, since every interface has a link-local IPv6 fe80::/10 address attached to it, which comes last on my Linux machine and so always overwrites any global IPv6 address in the report.

**Comment by robphoenix** [comment]
No pressure @siebenmann don't feel you have to fix this yourself, I'm happy to get to it in due course. I'm also happy to help with the PR process if you get stuck. 

> This is a bit more annoying in the IPv6 case

Yeah, for sure. I'll prioritise getting this fixed. Thanks again :+1:

**Comment by robphoenix** [comment]
closed by https://github.com/robphoenix/trawl/commit/432e7a2b4527cd8d5e423fbf0ab65c9a5d7ce399
